version: '3'

services:

   nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - "80:80"
      volumes:
        - ./infra/nginx/nginx.conf/:/etc/nginx/nginx.conf
        - ./static/:/usr/share/nginx/html


